### ISSUE TITLE
missing dependency: couchapp

### ISSUE THREAD

**Issue by streaps** [garbados/quilter#16]
same problem as in issue #13, this time the couchapp module is missing.

**Comment by garbados** [comment]
I am SO GOOD at this game. Will fix.

**Comment by garbados** [comment]
Addressed, sort of, in commit 9dfa53b6b4d6cb8816afec00ad42100872a5c24c.

Thing is, couchapp was already in the dependencies. That commit moved it out of `devDependencies`, but `npm install` should install those too. What steps did you take to get the missing dependency error?

**Comment by streaps** [comment]
I had couchapp installed, when I installed quilter. After removing the couchapp package, I've got the missing module error.

I'm new to nodejs and npm. It looks like a "npm install" inside the quilter directory does install the devDependencies, but "npm install quilter" does not fetch and install the devDependencies.

**Comment by garbados** [comment]
Yep, that's how it should work, and I was wrong to put couchapp into the dev dependencies. Fixed now. Thanks for bringing this up, and I'm sorry for the trouble!
